from litestar import Request
from base64 import b64encode
from copy import deepcopy
from os.path import exists
from hashlib import md5
import uuid
from server.const import (
    USER_JSON_PATH,
    CONFIG_PATH,
    BATTLE_REPLAY_JSON_PATH,
    GACHA_JSON_PATH,
    SKIN_TABLE_URL,
    CHARACTER_TABLE_URL,
    EQUIP_TABLE_URL,
    STORY_TABLE_URL,
    STAGE_TABLE_URL,
    SYNC_DATA_TEMPLATE_PATH,
    BATTLEEQUIP_TABLE_URL,
    DM_TABLE_URL,
    RETRO_TABLE_URL,
    HANDBOOK_INFO_TABLE_URL,
    MAILLIST_PATH,
    CHARM_TABLE_URL,
    ACTIVITY_TABLE_URL,
    SQUADS_PATH,
    STORY_REVIEW_TABLE_URL,
    ENEMY_HANDBOOK_TABLE_URL,
    MEDAL_TABLE_URL,
    RL_TABLE_URL,
    CHARWORD_TABLE_URL,
    SANDBOX_JSON_PATH,
    STORY_REVIEW_META_TABLE_URL,
    CRISIS_V2_JSON_BASE_PATH,
)
